# Only to be used for testing purposes

services:
  database:
    image: neo4j:5.23.0
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/StrongPsPsP5
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
